/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      // Palet warna resmi terbaru dari DESIGN.md / Stitch (dipakai Katalog Buah dst).
      // Nilainya sangat dekat dengan yang dipakai Register/Login sebelumnya, jadi
      // dua halaman itu tetap terlihat sama meski kita satukan ke sini.
      colors: {
        'surface-dim': '#d7dcd3',
        background: '#f6fbf2',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#ffb2be',
        'surface-tint': '#006e2f',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'surface-container-highest': '#dfe4db',
        'surface-container-low': '#f0f5ec',
        'primary-fixed': '#9af7a8',
        'on-tertiary-fixed-variant': '#80253d',
        'on-background': '#181d18',
        'primary-fixed-dim': '#7fda8e',
        surface: '#f6fbf2',
        'on-secondary-container': '#754900',
        'error-container': '#ffdad6',
        'inverse-surface': '#2c322c',
        error: '#ba1a1a',
        'on-surface': '#181d18',
        'on-secondary-fixed-variant': '#653e00',
        'surface-bright': '#f6fbf2',
        'on-tertiary-container': '#ffccd3',
        'on-primary-fixed-variant': '#005321',
        'surface-container-high': '#e5eae1',
        outline: '#6f7a6e',
        'secondary-container': '#fdb965',
        'tertiary-fixed': '#ffd9de',
        tertiary: '#80253d',
        'tertiary-container': '#9f3d54',
        'primary-container': '#006e2f',
        'on-tertiary-fixed': '#400015',
        'on-primary-fixed': '#002109',
        secondary: '#855300',
        primary: '#005322',
        'on-primary-container': '#91ee9f',
        'on-surface-variant': '#3f493f',
        'secondary-fixed': '#ffddb8',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#fdb965',
        'outline-variant': '#becabc',
        'surface-container': '#ebefe6',
        'inverse-on-surface': '#edf2e9',
        'on-secondary-fixed': '#2a1700',
        'surface-variant': '#dfe4db',
        'inverse-primary': '#7fda8e',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        // dipakai Register / Login
        'stack-md': '16px',
        'container-padding-desktop': '48px',
        'stack-lg': '32px',
        unit: '4px',
        'stack-sm': '8px',
        'container-padding-mobile': '16px',
        // dipakai Katalog Buah dst (skala spacing terbaru)
        gutter: '16px',
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        'label-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-price': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '26px', fontWeight: '400' }],
        'label-price': ['22px', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
